d={
    "class":{
        "student":{
            "name":"Yagnesh",
            "marks":{
                "physics":70,
                "history":80
                }
            }
        }
    }
print(d["class"]["student"]["marks"]["physics"])
